name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Install trunk from crates.io
      uses: baptiste0928/cargo-install@v2
      with:
        crate: trunk

    - name: Install wasm-bindgen-cli from crates.io
      uses: baptiste0928/cargo-install@v2
      with:
        crate: wasm-bindgen-cli

    - name: Clippy for API
      run: cargo clippy --package api

    - name: Clippy for WebApp
      run: cargo clippy --package webapp

    - name: Build API
      run: cargo build --package api

    - name: Build WebApp
      run: trunk build --package webapp

    - name: Test API
      run: cargo test --package api

    - name: Test WebApp
      run: cargo test --package webapp

